"""
intelligence/briefing_generator.py

Calls the Anthropic API to generate the daily briefing from the context document
assembled by context_builder.py.

Usage:
    python -m intelligence.briefing_generator --date 2026-03-17
    python -m intelligence.briefing_generator --date 2026-03-17 --dry-run
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import date, timedelta

import anthropic
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))

from intelligence.config import BRIEFING_DATE_FORMAT, MODEL_CONFIG, SYSTEM_PROMPT_TEMPLATE
from intelligence.context_builder import BriefingContext, build_briefing_context
from intelligence.logging_config import setup_logging

logger = setup_logging(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

WORD_COUNT_MIN = 200
WORD_COUNT_MAX = 1000
WORD_COUNT_TARGET = 600
BRIEFINGS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "briefings")


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Briefing:
    date: str
    content_slack: str          # Slack mrkdwn formatted
    content_plain: str          # plain text fallback
    model_used: str
    input_tokens: int
    output_tokens: int
    generation_time_seconds: float
    retry_count: int


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_for_slack(text: str, date_formatted: str) -> str:
    """Convert markdown text to Slack mrkdwn format."""
    # Convert **bold** -> *bold*
    text = re.sub(r"\*\*(.+?)\*\*", r"*\1*", text)

    # Convert ### Heading -> *HEADING* (bold caps on its own line)
    def _heading_to_slack(m: re.Match) -> str:
        heading = m.group(1).strip().upper()
        return f"\n*{heading}*"

    text = re.sub(r"^#{1,6}\s+(.+)$", _heading_to_slack, text, flags=re.MULTILINE)

    # Normalise bullet lists: ensure "- " or "• " (Slack renders both)
    text = re.sub(r"^\*\s+", "• ", text, flags=re.MULTILINE)

    # Trim extra blank lines (more than two consecutive)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = text.strip()

    now_str = time.strftime("%I:%M %p")
    header = f":sunrise: *Daily Briefing — {date_formatted}*\n"
    footer = f"\n_Generated by Sparkle & Shine AI at {now_str}_"
    return header + "\n" + text + footer


def _format_plain(text: str) -> str:
    """Strip all markdown/mrkdwn formatting for archiving."""
    # Remove bold markers
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    # Remove heading markers
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove italic/underscore
    text = re.sub(r"_(.+?)_", r"\1", text)
    # Remove bullet symbols that aren't plain dashes
    text = re.sub(r"^[•]\s+", "- ", text, flags=re.MULTILINE)
    return text.strip()


# ---------------------------------------------------------------------------
# Quality gate
# ---------------------------------------------------------------------------

def _word_count(text: str) -> int:
    return len(text.split())


def _distance_from_target(word_count: int) -> int:
    return abs(word_count - WORD_COUNT_TARGET)


# ---------------------------------------------------------------------------
# Archive helper
# ---------------------------------------------------------------------------

def _archive_briefing(briefing: Briefing) -> None:
    """Write briefing to briefings/briefing_{YYYY-MM-DD}.md."""
    os.makedirs(BRIEFINGS_DIR, exist_ok=True)
    filepath = os.path.join(BRIEFINGS_DIR, f"briefing_{briefing.date}.md")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# Daily Briefing — {briefing.date}\n\n")
        f.write(briefing.content_plain)
        f.write(
            f"\n\n---\n"
            f"Model: {briefing.model_used} | "
            f"Tokens in: {briefing.input_tokens} / out: {briefing.output_tokens} | "
            f"Time: {briefing.generation_time_seconds:.1f}s | "
            f"Retries: {briefing.retry_count}\n"
        )
    logger.info("Briefing archived to %s", filepath)


# ---------------------------------------------------------------------------
# Core generation function
# ---------------------------------------------------------------------------

def generate_briefing(context: BriefingContext, dry_run: bool = False) -> Briefing:
    """
    Generate the daily briefing using the Anthropic API.

    Parameters
    ----------
    context:
        The assembled BriefingContext from context_builder.build_briefing_context().
    dry_run:
        If True, skip the API call and return a placeholder Briefing.

    Returns
    -------
    Briefing
    """
    if dry_run:
        logger.info("DRY RUN: skipping Anthropic API call for date %s", context.date)
        print("\n--- Context document that would be sent ---\n")
        print(context.context_document)
        print("\n--- End of context document ---\n")
        return Briefing(
            date=context.date,
            content_slack=f"[DRY RUN] Would generate briefing for {context.date}",
            content_plain=f"[DRY RUN] Would generate briefing for {context.date}",
            model_used=MODEL_CONFIG["briefing_model"],
            input_tokens=0,
            output_tokens=0,
            generation_time_seconds=0.0,
            retry_count=0,
        )

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env

    system = SYSTEM_PROMPT_TEMPLATE
    user_message = context.context_document

    retry_count = 0
    start_time = time.monotonic()

    # --- First attempt ---
    logger.info(
        "Calling Anthropic API (model=%s) for date %s",
        MODEL_CONFIG["briefing_model"],
        context.date,
    )
    response = client.messages.create(
        model=MODEL_CONFIG["briefing_model"],
        max_tokens=MODEL_CONFIG["max_tokens_briefing"],
        temperature=MODEL_CONFIG["temperature_briefing"],
        system=system,
        messages=[{"role": "user", "content": user_message}],
    )

    first_text = response.content[0].text
    first_word_count = _word_count(first_text)
    input_tokens = response.usage.input_tokens
    output_tokens = response.usage.output_tokens

    if first_word_count < WORD_COUNT_MIN or first_word_count > WORD_COUNT_MAX:
        logger.warning(
            "Briefing word count %d outside target range (%d-%d); retrying",
            first_word_count,
            WORD_COUNT_MIN,
            WORD_COUNT_MAX,
        )
        retry_count = 1

        retry_message = (
            f"Your response was {first_word_count} words. Please regenerate the briefing "
            f"to be between 400-800 words. Keep all 6 sections."
        )
        retry_response = client.messages.create(
            model=MODEL_CONFIG["briefing_model"],
            max_tokens=MODEL_CONFIG["max_tokens_briefing"],
            temperature=MODEL_CONFIG["temperature_briefing"],
            system=system,
            messages=[
                {"role": "user", "content": user_message},
                {"role": "assistant", "content": first_text},
                {"role": "user", "content": retry_message},
            ],
        )

        second_text = retry_response.content[0].text
        second_word_count = _word_count(second_text)
        input_tokens += retry_response.usage.input_tokens
        output_tokens += retry_response.usage.output_tokens

        if second_word_count < WORD_COUNT_MIN or second_word_count > WORD_COUNT_MAX:
            logger.warning(
                "Retry word count %d also outside range; using closer result",
                second_word_count,
            )

        # Pick the candidate closest to the target word count
        if _distance_from_target(second_word_count) <= _distance_from_target(first_word_count):
            chosen_text = second_text
            chosen_word_count = second_word_count
        else:
            chosen_text = first_text
            chosen_word_count = first_word_count

        logger.info("Using candidate with word count %d", chosen_word_count)
    else:
        chosen_text = first_text
        chosen_word_count = first_word_count

    generation_time = time.monotonic() - start_time

    content_slack = _format_for_slack(chosen_text, context.date_formatted)
    content_plain = _format_plain(chosen_text)

    logger.info(
        "Briefing generated | model=%s | tokens_in=%d | tokens_out=%d | "
        "time=%.1fs | words=%d | retries=%d",
        MODEL_CONFIG["briefing_model"],
        input_tokens,
        output_tokens,
        generation_time,
        chosen_word_count,
        retry_count,
    )

    briefing = Briefing(
        date=context.date,
        content_slack=content_slack,
        content_plain=content_plain,
        model_used=MODEL_CONFIG["briefing_model"],
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        generation_time_seconds=generation_time,
        retry_count=retry_count,
    )

    _archive_briefing(briefing)
    return briefing


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _resolve_date(date_arg: str) -> str:
    today = date.today()
    if date_arg == "today":
        return str(today)
    if date_arg == "yesterday":
        return str(today - timedelta(days=1))
    return date_arg


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Sparkle & Shine daily briefing."
    )
    parser.add_argument(
        "--date",
        required=True,
        help="Briefing date as YYYY-MM-DD, 'today', or 'yesterday'.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the context document without calling the API.",
    )
    args = parser.parse_args()

    briefing_date = _resolve_date(args.date)

    from intelligence.logging_config import setup_logging as _setup
    _setup("intelligence")  # ensure root intelligence logger is configured

    db_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "sparkle_shine.db")
    context = build_briefing_context(db_path, briefing_date, briefings_dir=BRIEFINGS_DIR)
    briefing = generate_briefing(context, dry_run=args.dry_run)

    print(briefing.content_slack)


if __name__ == "__main__":
    main()
