#!/usr/bin/env python3
"""
extract_railway_env.py

Reads local credential sources (.env, token.json, .jobber_tokens.json,
.quickbooks_tokens.json, credentials.json) and writes a .env.railway file
ready to paste into Railway's variable editor.

Usage:
    python scripts/extract_railway_env.py

Output: .env.railway  (gitignored)
"""

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_env(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict, ignoring comments and blank lines."""
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()
    return env


def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def main() -> None:
    env_path = ROOT / ".env"
    if not env_path.exists():
        print(f"ERROR: {env_path} not found", file=sys.stderr)
        sys.exit(1)

    env = load_env(env_path)

    # ── OAuth token files ────────────────────────────────────────────────────
    jobber_tokens = load_json(ROOT / ".jobber_tokens.json")
    qbo_tokens = load_json(ROOT / ".quickbooks_tokens.json")
    google_token = load_json(ROOT / "token.json")

    google_client_id = google_token.get("client_id", "")
    google_client_secret = google_token.get("client_secret", "")
    google_refresh_token = google_token.get("refresh_token", "")

    # credentials.json may also carry client_id / client_secret
    creds_path = ROOT / "credentials.json"
    if creds_path.exists():
        creds = load_json(creds_path)
        # Handle both "installed" and "web" app credential formats
        app_creds = creds.get("installed") or creds.get("web") or {}
        google_client_id = google_client_id or app_creds.get("client_id", "")
        google_client_secret = google_client_secret or app_creds.get("client_secret", "")

    lines = [
        "# Generated by scripts/extract_railway_env.py — DO NOT COMMIT",
        "",
        "# ─── Database (set by Railway Postgres plugin) ───────────────────────────────",
        "DATABASE_URL=",
        "",
        "# ─── Anthropic ───────────────────────────────────────────────────────────────",
        f"ANTHROPIC_API_KEY={env.get('ANTHROPIC_API_KEY', '')}",
        "",
        "# ─── Pipedrive ───────────────────────────────────────────────────────────────",
        f"PIPEDRIVE_API_TOKEN={env.get('PIPEDRIVE_API_TOKEN', '')}",
        f"PIPEDRIVE_BASE_URL={env.get('PIPEDRIVE_BASE_URL', 'https://api.pipedrive.com/v1')}",
        "",
        "# ─── Jobber (OAuth 2.0) ──────────────────────────────────────────────────────",
        f"JOBBER_CLIENT_ID={env.get('JOBBER_CLIENT_ID', '')}",
        f"JOBBER_CLIENT_SECRET={env.get('JOBBER_CLIENT_SECRET', '')}",
        f"JOBBER_REFRESH_TOKEN={jobber_tokens.get('refresh_token', '')}",
        f"JOBBER_API_VERSION={env.get('JOBBER_API_VERSION', '2026-03-10')}",
        f"JOBBER_BASE_URL={env.get('JOBBER_BASE_URL', 'https://api.getjobber.com/api/graphql')}",
        "",
        "# ─── QuickBooks Online (OAuth 2.0) ───────────────────────────────────────────",
        f"QUICKBOOKS_CLIENT_ID={env.get('QUICKBOOKS_CLIENT_ID', '')}",
        f"QUICKBOOKS_CLIENT_SECRET={env.get('QUICKBOOKS_CLIENT_SECRET', '')}",
        f"QUICKBOOKS_REFRESH_TOKEN={qbo_tokens.get('refresh_token', '')}",
        f"QBO_COMPANY_ID={env.get('QBO_COMPANY_ID', env.get('QUICKBOOKS_COMPANY_ID', ''))}",
        f"QBO_BASE_URL={env.get('QBO_BASE_URL', 'https://sandbox-quickbooks.api.intuit.com/v3/company')}",
        "",
        "# ─── Google Workspace (OAuth 2.0) ────────────────────────────────────────────",
        f"GOOGLE_CLIENT_ID={google_client_id}",
        f"GOOGLE_CLIENT_SECRET={google_client_secret}",
        f"GOOGLE_REFRESH_TOKEN={google_refresh_token}",
        "",
        "# ─── HubSpot ─────────────────────────────────────────────────────────────────",
        f"HUBSPOT_ACCESS_TOKEN={env.get('HUBSPOT_ACCESS_TOKEN', '')}",
        f"HUBSPOT_BASE_URL={env.get('HUBSPOT_BASE_URL', 'https://api.hubapi.com')}",
        "",
        "# ─── Mailchimp ───────────────────────────────────────────────────────────────",
        f"MAILCHIMP_API_KEY={env.get('MAILCHIMP_API_KEY', '')}",
        f"MAILCHIMP_SERVER_PREFIX={env.get('MAILCHIMP_SERVER_PREFIX', '')}",
        f"MAILCHIMP_LIST_ID={env.get('MAILCHIMP_LIST_ID', '')}",
        "",
        "# ─── Asana ───────────────────────────────────────────────────────────────────",
        f"ASANA_ACCESS_TOKEN={env.get('ASANA_ACCESS_TOKEN', '')}",
        f"ASANA_WORKSPACE_GID={env.get('ASANA_WORKSPACE_GID', '')}",
        f"ASANA_TEAM_GID={env.get('ASANA_TEAM_GID', '')}",
        f"ASANA_PROJECT_SALES_PIPELINE_GID={env.get('ASANA_PROJECT_SALES_PIPELINE_GID', '')}",
        f"ASANA_PROJECT_MARKETING_CALENDAR_GID={env.get('ASANA_PROJECT_MARKETING_CALENDAR_GID', '')}",
        f"ASANA_PROJECT_ADMIN_OPERATIONS_GID={env.get('ASANA_PROJECT_ADMIN_OPERATIONS_GID', '')}",
        f"ASANA_PROJECT_CLIENT_SUCCESS_GID={env.get('ASANA_PROJECT_CLIENT_SUCCESS_GID', '')}",
        "",
        "# ─── Slack ───────────────────────────────────────────────────────────────────",
        f"SLACK_BOT_TOKEN={env.get('SLACK_BOT_TOKEN', '')}",
        f"SLACK_WORKSPACE_ID={env.get('SLACK_WORKSPACE_ID', '')}",
        f"SLACK_CHANNEL_GENERAL={env.get('SLACK_CHANNEL_GENERAL', '')}",
        f"SLACK_CHANNEL_SALES={env.get('SLACK_CHANNEL_SALES', '')}",
        f"SLACK_CHANNEL_SALES_PIPELINE={env.get('SLACK_CHANNEL_SALES_PIPELINE', '')}",
        f"SLACK_CHANNEL_OPERATIONS={env.get('SLACK_CHANNEL_OPERATIONS', '')}",
        f"SLACK_CHANNEL_DAILY_BRIEFING={env.get('SLACK_CHANNEL_DAILY_BRIEFING', '')}",
        f"SLACK_CHANNEL_NEW_CLIENTS={env.get('SLACK_CHANNEL_NEW_CLIENTS', '')}",
        f"SLACK_CHANNEL_REVIEWS_AND_FEEDBACK={env.get('SLACK_CHANNEL_REVIEWS_AND_FEEDBACK', '')}",
        f"SLACK_CHANNEL_SOCIAL={env.get('SLACK_CHANNEL_SOCIAL', '')}",
        f"SLACK_CHANNEL_ALL={env.get('SLACK_CHANNEL_ALL', '')}",
    ]

    out_path = ROOT / ".env.railway"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Written: {out_path}")
    print()
    print("Next steps:")
    print("  1. Fill in DATABASE_URL after attaching a Railway Postgres plugin.")
    print("  2. Paste the contents into Railway > Variables (or use the Railway CLI:")
    print("       railway variables set < .env.railway)")
    print("  3. Never commit .env.railway — it is gitignored.")


if __name__ == "__main__":
    main()
