"""
Step 7 — Populate Google Workspace for Sparkle & Shine Cleaning Co.

Creates
-------
  • 8 Google Docs  (Claude-generated content via claude-sonnet-4-0)
  • 4 Google Sheets (rate card, budget tracker, supply inventory, vehicle log)
  • 15 Google Calendar events (site visits, team meetings, orientations, 1:1s)
  • SQLite ``documents`` + ``document_index`` rows for all Docs/Sheets
  • SQLite ``calendar_events`` rows for all events
  • Updates config/tool_ids.json with all Google file/event IDs

Usage
-----
    python -m setup.populate_workspace
"""

import os
import sys
import json
import re
import sqlite3
from typing import Optional, Dict

import anthropic

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from credentials import get_credential
from auth.google_auth import (
    get_docs_service,
    get_sheets_service,
    get_calendar_service,
)
from database.schema import get_connection, init_db

# ------------------------------------------------------------------ #
# Paths
# ------------------------------------------------------------------ #
_PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))
_TOOL_IDS_PATH = os.path.join(_PROJECT_ROOT, "config", "tool_ids.json")
_DB_PATH = os.path.join(_PROJECT_ROOT, "sparkle_shine.db")

# ------------------------------------------------------------------ #
# Anthropic client (lazy)
# ------------------------------------------------------------------ #
_MODEL = "claude-sonnet-4-0"
_anthropic_client: Optional[anthropic.Anthropic] = None


def _get_client() -> anthropic.Anthropic:
    global _anthropic_client
    if _anthropic_client is None:
        _anthropic_client = anthropic.Anthropic(
            api_key=get_credential("ANTHROPIC_API_KEY")
        )
    return _anthropic_client


def _generate(prompt: str, max_tokens: int = 1200) -> str:
    """Return text generated by Claude (streaming)."""
    with _get_client().messages.stream(
        model=_MODEL,
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    ) as stream:
        final = stream.get_final_message()
    return next(b.text for b in final.content if b.type == "text")


# ------------------------------------------------------------------ #
# Document definitions  (8 Google Docs)
# ------------------------------------------------------------------ #
_DOCS = [
    {
        "key": "employee_handbook",
        "title": "Employee Handbook — Sparkle & Shine Cleaning Co.",
        "doc_type": "sop",
        "max_tokens": 1400,
        "prompt": (
            "Write a professional employee handbook for Sparkle & Shine Cleaning Co., "
            "a residential and commercial cleaning company in Austin, TX owned by "
            "Maria Gonzalez. Include these labeled sections: 1) Welcome & Company Values, "
            "2) Work Hours & Scheduling, 3) Dress Code & Professional Appearance, "
            "4) Client Interaction Standards, 5) Safety Protocols, 6) Quality Standards, "
            "7) Compensation & Benefits, 8) Time Off Policy, 9) Code of Conduct. "
            "Tone: warm, practical, and professional. ~800 words."
        ),
    },
    {
        "key": "service_quality_checklist",
        "title": "Service Standards & Quality Checklists",
        "doc_type": "sop",
        "max_tokens": 1200,
        "prompt": (
            "Create detailed service standards and room-by-room quality checklists for "
            "Sparkle & Shine Cleaning Co. Include separate checklists for: "
            "Standard Residential Clean, Deep Clean, Move-In/Move-Out Clean, and "
            "Commercial Nightly Clean. Also include a quality inspection rubric "
            "(1–5 rating scale per category). Clear headers and bullet points. ~700 words."
        ),
    },
    {
        "key": "client_onboarding_guide",
        "title": "New Client Welcome & Onboarding Guide",
        "doc_type": "sop",
        "max_tokens": 1100,
        "prompt": (
            "Write a client onboarding welcome guide for Sparkle & Shine Cleaning Co. "
            "in Austin, TX. Include: welcome message from owner Maria Gonzalez, "
            "what to expect on your first service, how to prepare your home or office, "
            "our vetted and background-checked team, eco-friendly cleaning product options, "
            "scheduling and communication channels, and our quality guarantee policy. "
            "Warm, welcoming tone. ~650 words."
        ),
    },
    {
        "key": "safety_chemical_manual",
        "title": "Safety & Chemical Handling Manual",
        "doc_type": "sop",
        "max_tokens": 1100,
        "prompt": (
            "Write a safety and chemical handling manual for cleaning staff at "
            "Sparkle & Shine Cleaning Co. Cover: required PPE by task type, "
            "safe chemical handling and storage, critical mixing rules (never mix "
            "bleach with ammonia, etc.), SDS sheet locations, injury and incident "
            "reporting procedures, ergonomic safety (lifting, repetitive motion), "
            "and emergency contacts. Numbered sections, professional safety tone. ~650 words."
        ),
    },
    {
        "key": "sales_proposal_templates",
        "title": "Sales Scripts & Proposal Templates",
        "doc_type": "template",
        "max_tokens": 1400,
        "prompt": (
            "Write sales scripts and proposal templates for Sparkle & Shine Cleaning Co. "
            "Include: phone inquiry response script, site visit agenda template, "
            "residential proposal template (with service tier pricing table), "
            "commercial proposal template (per-square-foot pricing), "
            "a 3-email follow-up sequence (Day 1, Day 4, Day 10), "
            "and an objection handling guide. Professional sales tone. ~850 words."
        ),
    },
    {
        "key": "marketing_playbook",
        "title": "Marketing & Social Media Playbook",
        "doc_type": "sop",
        "max_tokens": 1300,
        "prompt": (
            "Create a marketing and social media playbook for Sparkle & Shine Cleaning Co. "
            "in Austin, TX. Include: brand voice and messaging guidelines, "
            "Instagram content calendar (weekly posting themes), Facebook strategy, "
            "Google Business Profile optimization tips, monthly email newsletter cadence, "
            "referral program structure (reward amounts), seasonal campaign ideas "
            "(spring cleaning, move season, holiday prep), and a 5-star review "
            "generation strategy. Practical, actionable format. ~750 words."
        ),
    },
    {
        "key": "vendor_supplier_directory",
        "title": "Vendor & Supplier Directory",
        "doc_type": "sop",
        "max_tokens": 1000,
        "prompt": (
            "Create a vendor and supplier directory for Sparkle & Shine Cleaning Co. "
            "List realistic fictional suppliers for: cleaning chemicals (3 vendors), "
            "cleaning equipment and vacuums (2 vendors), uniforms and PPE (1 vendor), "
            "vehicle maintenance (1 vendor), and business insurance (1 vendor). "
            "For each include: company name, contact name, phone, email, account number, "
            "payment terms, what we purchase, and any notes. Austin, TX area. ~600 words."
        ),
    },
    {
        "key": "fy2026_growth_plan",
        "title": "FY2026 Strategic Growth Plan",
        "doc_type": "sop",
        "max_tokens": 1500,
        "prompt": (
            "Write a strategic growth plan for Sparkle & Shine Cleaning Co. "
            "for fiscal year 2026 (April 2025 – March 2026). Include: "
            "executive summary, current state (residential and commercial client base, "
            "18-person team, 4 service crews, ~$1.5M in annual revenue), "
            "$2M annual revenue target, four key initiatives: "
            "1. expand commercial portfolio, 2. grow team to 23 staff, "
            "3. launch referral program, 4. upgrade scheduling and CRM tools; "
            "quarterly milestones, KPIs (revenue, client retention, crew utilization, NPS), "
            "and risk mitigation. Business planning format. Owner: Maria Gonzalez. ~900 words."
        ),
    },
]


# ------------------------------------------------------------------ #
# Sheet definitions  (4 Google Sheets)
# ------------------------------------------------------------------ #
_SHEETS = [
    {
        "key": "rate_card",
        "title": "Service Rate Card — Sparkle & Shine",
        "doc_type": "spreadsheet",
        "tab_name": "Rate Card",
        "headers": [
            "Service Name", "Category", "Duration (min)",
            "Base Price ($)", "Weekly Rate ($)", "Biweekly Rate ($)",
            "Monthly Rate ($)", "Notes",
        ],
        "rows": [
            ["Standard Residential Clean", "Residential", 120, 150.00, 135.00, 150.00, 165.00, "Rate varies by sq ft"],
            ["Deep Clean", "Residential", 210, 275.00, "", "", "", "One-time service"],
            ["Move-In/Move-Out Clean", "Residential", 240, 325.00, "", "", "", "Includes cabinets & appliances"],
            ["Recurring Weekly", "Residential", 120, 135.00, 135.00, "", "", "Loyalty discount applied"],
            ["Recurring Biweekly", "Residential", 120, 150.00, "", 150.00, "", "Most popular plan"],
            ["Recurring Monthly", "Residential", 120, 165.00, "", "", 165.00, ""],
            ["Commercial Nightly Clean", "Commercial", 180, "", "", "", "", "$0.12/sqft; min 1,000 sqft"],
        ],
    },
    {
        "key": "budget_tracker",
        "title": "Monthly Budget Tracker FY2026 — Sparkle & Shine",
        "doc_type": "spreadsheet",
        "tab_name": "Budget Tracker",
        "headers": [
            "Month", "Revenue Target ($)", "Actual Revenue ($)",
            "Supplies ($)", "Equipment ($)", "Vehicle ($)",
            "Employee Wages ($)", "Marketing ($)", "Office ($)",
            "Insurance ($)", "Net Profit ($)",
        ],
        "rows": [
            ["Apr 2025", 120000, 118500, 3200, 1800, 4100, 37000, 2400, 1100, 2700, 66200],
            ["May 2025", 125000, 126800, 3400,  900, 4200, 38500, 2800, 1100, 2700, 73200],
            ["Jun 2025", 130000, 129200, 3600, 2100, 4300, 40000, 3200, 1200, 2700, 72100],
            ["Jul 2025", 135000, 132500, 3500, 1500, 4500, 41000, 3000, 1200, 2700, 75100],
            ["Aug 2025", 138000, 140200, 3700, 1200, 4400, 42000, 2800, 1200, 2700, 82200],
            ["Sep 2025", 140000, 137600, 3600, 1800, 4400, 42000, 3200, 1300, 2700, 78600],
            ["Oct 2025", 143000, 145100, 3800, 2200, 4600, 43500, 3400, 1300, 2700, 83600],
            ["Nov 2025", 145000, 148300, 3900, 1600, 4500, 44000, 2600, 1300, 2700, 87700],
            ["Dec 2025", 148000, 152400, 4200, 2400, 5000, 46000, 2200, 1400, 2700, 88500],
            ["Jan 2026", 150000, 149800, 3700, 1900, 4800, 45000, 3800, 1400, 2700, 86500],
            ["Feb 2026", 152000, 153600, 3900, 1400, 4700, 46000, 4200, 1400, 2700, 89300],
            ["Mar 2026", 155000, "",     "",   "",   "",   "",    "",   "",   "",   ""],
        ],
    },
    {
        "key": "supply_inventory",
        "title": "Supply & Inventory Log — Sparkle & Shine",
        "doc_type": "spreadsheet",
        "tab_name": "Inventory",
        "headers": [
            "Item", "Category", "Unit", "Unit Cost ($)",
            "Qty in Stock", "Reorder Level", "Supplier", "Last Restocked",
        ],
        "rows": [
            ["Multi-Surface Cleaner",      "Chemicals",   "Gallon",      8.50,  24, 10, "CleanPro Supplies",        "2026-03-01"],
            ["Disinfectant Spray",          "Chemicals",   "32oz Bottle", 4.25,  48, 20, "CleanPro Supplies",        "2026-03-01"],
            ["Bathroom Cleaner",            "Chemicals",   "32oz Bottle", 3.75,  36, 15, "CleanPro Supplies",        "2026-02-15"],
            ["Glass Cleaner",               "Chemicals",   "32oz Bottle", 3.50,  30, 12, "CleanPro Supplies",        "2026-02-15"],
            ["Bleach",                      "Chemicals",   "Gallon",      5.00,  18,  8, "Austin Janitorial Supply", "2026-02-20"],
            ["Degreaser",                   "Chemicals",   "Gallon",      9.00,  12,  6, "Austin Janitorial Supply", "2026-02-20"],
            ["Microfiber Cloths (12-pk)",   "Equipment",  "Pack",        14.00,  20,  8, "CleanPro Supplies",        "2026-03-01"],
            ["Mop Heads",                   "Equipment",  "Each",         6.50,  15,  6, "CleanPro Supplies",        "2026-02-01"],
            ["Scrub Brushes",               "Equipment",  "Each",         3.25,  25, 10, "CleanPro Supplies",        "2026-01-15"],
            ["Rubber Gloves M",             "PPE",         "Pair",         2.00,  40, 20, "Safety First Supplies",    "2026-03-05"],
            ["Rubber Gloves L",             "PPE",         "Pair",         2.00,  35, 20, "Safety First Supplies",    "2026-03-05"],
            ["Disposable Masks (50-pk)",    "PPE",         "Box",         12.00,   8,  4, "Safety First Supplies",    "2026-02-10"],
            ["Vacuum Bags Hoover (3-pk)",   "Equipment",  "Pack",         9.50,  12,  5, "Austin Janitorial Supply", "2026-02-01"],
            ["Toilet Bowl Cleaner",         "Chemicals",   "32oz Bottle", 3.25,  28, 12, "CleanPro Supplies",        "2026-03-01"],
            ["Floor Mopping Solution",      "Chemicals",   "Gallon",      7.75,  16,  8, "Austin Janitorial Supply", "2026-02-20"],
            ["Paper Towels (case/12)",      "Consumables", "Case",        28.00,   6,  3, "Costco Business",          "2026-03-08"],
            ["Trash Bags 13-gal (100ct)",   "Consumables", "Box",         18.50,   5,  2, "Costco Business",          "2026-03-08"],
            ["Trash Bags 33-gal (50ct)",    "Consumables", "Box",         22.00,   4,  2, "Costco Business",          "2026-03-08"],
            ["Spray Bottles",               "Equipment",  "Each",         2.50,  30, 15, "CleanPro Supplies",        "2026-01-20"],
            ["Squeegee",                    "Equipment",  "Each",         8.00,  10,  4, "CleanPro Supplies",        "2026-01-20"],
        ],
    },
    {
        "key": "vehicle_equipment_log",
        "title": "Vehicle & Equipment Log — Sparkle & Shine",
        "doc_type": "spreadsheet",
        "tab_name": "Fleet & Equipment",
        "headers": [
            "Asset ID", "Description", "Type", "Year/Model",
            "License/Serial #", "Assigned Crew", "Last Service Date",
            "Next Service Due", "Odometer/Hours", "Notes",
        ],
        "rows": [
            ["VAN-001",    "Ford Transit 250 Cargo Van",        "Vehicle",   "2021 Ford Transit",      "TX-APT8834",      "Crew A - Westside",       "2026-02-10", "2026-05-10", "87,420 mi", "Oil change done"],
            ["VAN-002",    "Ford Transit 250 Cargo Van",        "Vehicle",   "2022 Ford Transit",      "TX-BKL2291",      "Crew B - North/Domain",   "2026-01-28", "2026-04-28", "64,110 mi", "New tires Jan 2026"],
            ["VAN-003",    "Ford Transit 250 Cargo Van",        "Vehicle",   "2022 Ford Transit",      "TX-CQM5567",      "Crew C - East Austin",    "2026-02-20", "2026-05-20", "58,230 mi", ""],
            ["VAN-004",    "Ram ProMaster Cargo Van",           "Vehicle",   "2023 Ram ProMaster",     "TX-DPR9901",      "Crew D - South/Buda",     "2026-03-05", "2026-06-05", "31,850 mi", "Newest vehicle"],
            ["VAC-001",    "Hoover Commercial Upright",         "Equipment", "Hoover CH30000",         "SN-HC3000-4421",  "Crew A - Westside",       "2026-01-15", "2026-07-15", "620 hrs",   "Belt replaced"],
            ["VAC-002",    "Hoover Commercial Upright",         "Equipment", "Hoover CH30000",         "SN-HC3000-5892",  "Crew B - North/Domain",   "2025-12-01", "2026-06-01", "740 hrs",   ""],
            ["VAC-003",    "Bissell BigGreen Commercial",       "Equipment", "Bissell BGU1937T",       "SN-BB1937-3310",  "Crew C - East Austin",    "2026-02-01", "2026-08-01", "410 hrs",   ""],
            ["VAC-004",    "Hoover Commercial Upright",         "Equipment", "Hoover CH30000",         "SN-HC3000-7734",  "Crew D - South/Buda",     "2026-03-01", "2026-09-01", "180 hrs",   "New Jan 2026"],
            ["MOP-SYS-01", "Commercial Mop & Wringer Cart",    "Equipment", "Rubbermaid FG617388",    "SN-RM617-1122",   "Crew C - East Austin",    "2025-11-01", "2026-05-01", "N/A",       "Commercial clients only"],
            ["SV-CART-01", "Stainless Steel Cleaning Cart",    "Equipment", "Rubbermaid FG9T6600",    "SN-RM9T6-9981",   "Crew D - South/Buda",     "2025-10-15", "2026-04-15", "N/A",       "Commercial clients only"],
        ],
    },
]


# ------------------------------------------------------------------ #
# Calendar event definitions  (15 events)
# ------------------------------------------------------------------ #
_CALENDAR_ID = "primary"
_TIMEZONE = "America/Chicago"

_EVENTS = [
    {
        "key": "cal_001",
        "title": "Site Visit: Monarch Business Park",
        "event_type": "site_visit",
        "start": "2026-02-03T09:00:00",
        "end":   "2026-02-03T10:30:00",
        "description": "Site visit with property manager at Monarch Business Park (55,000 sqft office complex). Scope: nightly commercial cleaning proposal.",
        "attendees": ["maria@sparkleshine.com"],
    },
    {
        "key": "cal_002",
        "title": "Weekly Team Meeting — Feb Week 2",
        "event_type": "team_meeting",
        "start": "2026-02-10T10:00:00",
        "end":   "2026-02-10T11:00:00",
        "description": "All-hands weekly operations meeting. Agenda: scheduling updates, quality feedback, supply needs, new hire announcements.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_003",
        "title": "Site Visit: Summit Office Suites",
        "event_type": "site_visit",
        "start": "2026-02-14T14:00:00",
        "end":   "2026-02-14T15:30:00",
        "description": "Walk-through of Summit Office Suites (12,000 sqft, 3 floors). Prospective commercial nightly cleaning contract.",
        "attendees": ["maria@sparkleshine.com"],
    },
    {
        "key": "cal_004",
        "title": "New Hire Orientation — February Cohort",
        "event_type": "orientation",
        "start": "2026-02-17T09:00:00",
        "end":   "2026-02-17T12:00:00",
        "description": "Onboarding orientation for 3 new cleaning technicians. Topics: company values, safety protocols, service standards, scheduling system.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_005",
        "title": "Vendor Meeting: CleanPro Supplies Annual Review",
        "event_type": "vendor_meeting",
        "start": "2026-02-24T11:00:00",
        "end":   "2026-02-24T12:00:00",
        "description": "Annual contract review with CleanPro Supplies rep. Agenda: pricing for FY2026, new eco-friendly product line, volume discount negotiation.",
        "attendees": ["maria@sparkleshine.com"],
    },
    {
        "key": "cal_006",
        "title": "Maria & Patricia 1:1 — February",
        "event_type": "one_on_one",
        "start": "2026-03-03T15:00:00",
        "end":   "2026-03-03T16:00:00",
        "description": "Monthly 1:1 between Maria Gonzalez (Owner) and Patricia Nguyen (Operations Manager). Review KPIs, team performance, upcoming hires.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_007",
        "title": "Weekly Team Meeting — Mar Week 2",
        "event_type": "team_meeting",
        "start": "2026-03-10T10:00:00",
        "end":   "2026-03-10T11:00:00",
        "description": "All-hands weekly operations meeting. Spring scheduling ramp-up, quality checklist updates, Q1 performance review preview.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_008",
        "title": "Site Visit: Riverside Medical Clinic",
        "event_type": "site_visit",
        "start": "2026-03-13T09:00:00",
        "end":   "2026-03-13T10:30:00",
        "description": "Site evaluation at Riverside Medical Clinic (8,500 sqft). Medical-grade cleaning requirements. Requires OSHA compliance checklist.",
        "attendees": ["maria@sparkleshine.com"],
    },
    {
        "key": "cal_009",
        "title": "Q1 FY2026 Business Review",
        "event_type": "business_review",
        "start": "2026-03-17T13:00:00",
        "end":   "2026-03-17T15:00:00",
        "description": "Quarterly business review with leadership team. Q1 actuals vs targets, pipeline status, Q2 staffing plan, marketing performance.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_010",
        "title": "Weekly Team Meeting — Mar Week 4",
        "event_type": "team_meeting",
        "start": "2026-03-20T10:00:00",
        "end":   "2026-03-20T11:00:00",
        "description": "All-hands weekly operations meeting. Spring ramp-up scheduling, new hire onboarding prep.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_011",
        "title": "New Hire Orientation — Spring Cohort",
        "event_type": "orientation",
        "start": "2026-03-24T09:00:00",
        "end":   "2026-03-24T12:00:00",
        "description": "Spring hiring cohort orientation for 2 new cleaning technicians. Full-day onboarding including field shadowing with Crew A.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_012",
        "title": "Maria & Patricia 1:1 — March",
        "event_type": "one_on_one",
        "start": "2026-03-27T15:00:00",
        "end":   "2026-03-27T16:00:00",
        "description": "Monthly 1:1. Agenda: Q2 staffing plan, commercial pipeline review, marketing spend for spring season.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_013",
        "title": "Vendor Meeting: Equipment Maintenance Annual Review",
        "event_type": "vendor_meeting",
        "start": "2026-03-31T11:00:00",
        "end":   "2026-03-31T12:00:00",
        "description": "Annual review with Austin Equipment Services. Van maintenance schedule for Q2, vacuum service plans, new equipment purchases.",
        "attendees": ["maria@sparkleshine.com"],
    },
    {
        "key": "cal_014",
        "title": "Weekly Team Meeting — Apr Week 1",
        "event_type": "team_meeting",
        "start": "2026-04-02T10:00:00",
        "end":   "2026-04-02T11:00:00",
        "description": "First team meeting of Q2. Spring cleaning season launch, crew assignments, new client onboarding updates.",
        "attendees": ["maria@sparkleshine.com", "patricia@sparkleshine.com"],
    },
    {
        "key": "cal_015",
        "title": "Site Visit: TechHub Austin",
        "event_type": "site_visit",
        "start": "2026-04-07T09:00:00",
        "end":   "2026-04-07T10:30:00",
        "description": "Site visit at TechHub Austin coworking space (22,000 sqft, 6 days/week). High-potential commercial contract. Referred by existing client.",
        "attendees": ["maria@sparkleshine.com"],
    },
]


# ------------------------------------------------------------------ #
# Utilities
# ------------------------------------------------------------------ #
def _load_tool_ids() -> dict:
    with open(_TOOL_IDS_PATH) as f:
        return json.load(f)


def _save_tool_ids(data: dict) -> None:
    with open(_TOOL_IDS_PATH, "w") as f:
        json.dump(data, f, indent=2)


def _extract_keywords(text: str, max_kw: int = 15) -> str:
    """Return comma-separated top keywords extracted from text."""
    stop = {
        "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
        "of", "with", "is", "are", "was", "were", "be", "been", "have", "has",
        "had", "do", "does", "did", "will", "would", "could", "should", "may",
        "this", "that", "these", "those", "it", "its", "we", "our", "your",
        "their", "as", "by", "from", "into", "all", "each", "any", "also",
        "not", "no", "only", "so", "than", "too", "very", "just", "more",
    }
    words = re.findall(r"[a-zA-Z]{4,}", text.lower())
    freq: Dict[str, int] = {}
    for w in words:
        if w not in stop:
            freq[w] = freq.get(w, 0) + 1
    top = sorted(freq, key=lambda k: freq[k], reverse=True)[:max_kw]
    return ", ".join(top)


def _next_doc_id(conn: sqlite3.Connection) -> str:
    row = conn.execute(
        "SELECT id FROM documents ORDER BY id DESC LIMIT 1"
    ).fetchone()
    n = int(row["id"].split("-")[-1]) + 1 if row else 1
    return f"SS-DOC-{n:04d}"


def _next_cal_id(conn: sqlite3.Connection) -> str:
    row = conn.execute(
        "SELECT id FROM calendar_events ORDER BY id DESC LIMIT 1"
    ).fetchone()
    n = int(row["id"].split("-")[-1]) + 1 if row else 1
    return f"SS-CAL-{n:04d}"


# ------------------------------------------------------------------ #
# Google Docs
# ------------------------------------------------------------------ #
def _create_google_doc(docs_svc, title: str, content: str) -> str:
    """Create a Google Doc, insert content at index 1, return document ID."""
    doc = docs_svc.documents().create(body={"title": title}).execute()
    doc_id = doc["documentId"]
    docs_svc.documents().batchUpdate(
        documentId=doc_id,
        body={
            "requests": [
                {
                    "insertText": {
                        "location": {"index": 1},
                        "text": content,
                    }
                }
            ]
        },
    ).execute()
    return doc_id


def _populate_docs(docs_svc, conn, tool_ids, created, skipped):
    doc_ids = tool_ids.setdefault("google", {}).setdefault("docs", {})

    for defn in _DOCS:
        key = defn["key"]
        title = defn["title"]

        if key in doc_ids:
            skipped.append(f"Doc '{title}'")
            continue

        print(f"  [doc] Generating: {title} ...", end=" ", flush=True)
        content = _generate(defn["prompt"], defn["max_tokens"])
        print("generated.", end=" ", flush=True)

        google_id = _create_google_doc(docs_svc, title, content)
        print(f"created ({google_id})")
        doc_ids[key] = google_id

        # SQLite: documents row
        canonical_id = _next_doc_id(conn)
        keywords = _extract_keywords(content)
        conn.execute(
            """
            INSERT INTO documents
                (id, title, doc_type, platform, google_file_id,
                 content_text, keywords, last_indexed_at)
            VALUES (?, ?, ?, 'google_docs', ?, ?, ?, datetime('now'))
            """,
            (canonical_id, title, defn["doc_type"], google_id,
             content[:5000], keywords),
        )

        # SQLite: document_index chunks (1 000-char chunks)
        for i in range(0, len(content), 1000):
            chunk = content[i : i + 1000]
            conn.execute(
                """
                INSERT INTO document_index (doc_id, chunk_text, keywords, source_title)
                VALUES (?, ?, ?, ?)
                """,
                (canonical_id, chunk, _extract_keywords(chunk, 8), title),
            )

        conn.commit()
        created.append(f"Doc '{title}' → {google_id}")


# ------------------------------------------------------------------ #
# Google Sheets
# ------------------------------------------------------------------ #
_HEADER_BG = {"red": 0.18, "green": 0.48, "blue": 0.58}
_HEADER_FG = {"red": 1.0,  "green": 1.0,  "blue": 1.0}
_ALT_ROW_BG = {"red": 0.93, "green": 0.96, "blue": 0.98}


def _create_google_sheet(sheets_svc, title: str, tab_name: str, headers: list, rows: list) -> str:
    """Create a Sheet, write data, apply header + alternating-row formatting."""
    spreadsheet = sheets_svc.spreadsheets().create(
        body={
            "properties": {"title": title},
            "sheets": [{"properties": {"title": tab_name}}],
        }
    ).execute()
    ss_id = spreadsheet["spreadsheetId"]
    sheet_id = spreadsheet["sheets"][0]["properties"]["sheetId"]

    # Write headers + data
    all_rows = [headers] + [[str(v) for v in row] for row in rows]
    sheets_svc.spreadsheets().values().update(
        spreadsheetId=ss_id,
        range=f"{tab_name}!A1",
        valueInputOption="USER_ENTERED",
        body={"values": all_rows},
    ).execute()

    num_cols = len(headers)
    fmt_requests = []

    # Bold + coloured header row
    fmt_requests.append({
        "repeatCell": {
            "range": {
                "sheetId": sheet_id,
                "startRowIndex": 0, "endRowIndex": 1,
                "startColumnIndex": 0, "endColumnIndex": num_cols,
            },
            "cell": {
                "userEnteredFormat": {
                    "backgroundColor": _HEADER_BG,
                    "textFormat": {"foregroundColor": _HEADER_FG, "bold": True},
                }
            },
            "fields": "userEnteredFormat(backgroundColor,textFormat)",
        }
    })

    # Alternating rows (every odd data row)
    for idx in range(len(rows)):
        if idx % 2 == 1:
            fmt_requests.append({
                "repeatCell": {
                    "range": {
                        "sheetId": sheet_id,
                        "startRowIndex": idx + 1, "endRowIndex": idx + 2,
                        "startColumnIndex": 0, "endColumnIndex": num_cols,
                    },
                    "cell": {
                        "userEnteredFormat": {"backgroundColor": _ALT_ROW_BG}
                    },
                    "fields": "userEnteredFormat(backgroundColor)",
                }
            })

    # Auto-resize columns
    fmt_requests.append({
        "autoResizeDimensions": {
            "dimensions": {
                "sheetId": sheet_id,
                "dimension": "COLUMNS",
                "startIndex": 0,
                "endIndex": num_cols,
            }
        }
    })

    sheets_svc.spreadsheets().batchUpdate(
        spreadsheetId=ss_id,
        body={"requests": fmt_requests},
    ).execute()

    return ss_id


def _populate_sheets(sheets_svc, conn, tool_ids, created, skipped):
    sheet_ids = tool_ids.setdefault("google", {}).setdefault("sheets", {})

    for defn in _SHEETS:
        key = defn["key"]
        title = defn["title"]

        if key in sheet_ids:
            skipped.append(f"Sheet '{title}'")
            continue

        print(f"  [sheet] Creating: {title} ...", end=" ", flush=True)
        ss_id = _create_google_sheet(
            sheets_svc, title, defn["tab_name"],
            defn["headers"], defn["rows"],
        )
        print(f"done ({ss_id})")
        sheet_ids[key] = ss_id

        # SQLite: documents row
        canonical_id = _next_doc_id(conn)
        kw_text = title + " " + " ".join(defn["headers"])
        conn.execute(
            """
            INSERT INTO documents
                (id, title, doc_type, platform, google_file_id,
                 content_text, keywords, last_indexed_at)
            VALUES (?, ?, 'spreadsheet', 'google_sheets', ?, ?, ?, datetime('now'))
            """,
            (canonical_id, title, ss_id,
             ", ".join(defn["headers"]), _extract_keywords(kw_text)),
        )
        conn.commit()
        created.append(f"Sheet '{title}' → {ss_id}")


# ------------------------------------------------------------------ #
# Google Calendar
# ------------------------------------------------------------------ #
def _populate_calendar(cal_svc, conn, tool_ids, created, skipped):
    cal_event_ids = tool_ids.setdefault("google", {}).setdefault("calendar_events", {})

    for ev in _EVENTS:
        key = ev["key"]
        title = ev["title"]

        if key in cal_event_ids:
            skipped.append(f"Event '{title}'")
            continue

        print(f"  [cal] Creating: {title} ...", end=" ", flush=True)
        result = cal_svc.events().insert(
            calendarId=_CALENDAR_ID,
            body={
                "summary": title,
                "description": ev["description"],
                "start": {"dateTime": ev["start"], "timeZone": _TIMEZONE},
                "end":   {"dateTime": ev["end"],   "timeZone": _TIMEZONE},
                "attendees": [{"email": e} for e in ev.get("attendees", [])],
            },
        ).execute()
        google_event_id = result["id"]
        print(f"done ({google_event_id})")
        cal_event_ids[key] = google_event_id

        # SQLite: calendar_events row
        canonical_id = _next_cal_id(conn)
        conn.execute(
            """
            INSERT INTO calendar_events
                (id, title, event_type, start_datetime, end_datetime, attendees, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                canonical_id, title, ev["event_type"],
                ev["start"], ev["end"],
                json.dumps(ev.get("attendees", [])),
                ev["description"],
            ),
        )
        conn.commit()
        created.append(f"Event '{title}' → {google_event_id}")


# ------------------------------------------------------------------ #
# Main
# ------------------------------------------------------------------ #
def main():
    print("\n=== Step 7: Populate Google Workspace ===\n")

    init_db(_DB_PATH)
    conn = get_connection(_DB_PATH)
    tool_ids = _load_tool_ids()

    created = []
    skipped = []

    # 1. Google Docs
    print("── Google Docs ──────────────────────────────────────────")
    docs_svc = get_docs_service()
    _populate_docs(docs_svc, conn, tool_ids, created, skipped)
    _save_tool_ids(tool_ids)

    # 2. Google Sheets
    print("\n── Google Sheets ────────────────────────────────────────")
    sheets_svc = get_sheets_service()
    _populate_sheets(sheets_svc, conn, tool_ids, created, skipped)
    _save_tool_ids(tool_ids)

    # 3. Google Calendar
    print("\n── Google Calendar ──────────────────────────────────────")
    cal_svc = get_calendar_service()
    _populate_calendar(cal_svc, conn, tool_ids, created, skipped)
    _save_tool_ids(tool_ids)

    conn.close()

    # Summary
    sep = "=" * 56
    print(f"\n{sep}")
    print(f"  {'CREATED':<10}  {len(created):>3} items")
    print(f"  {'SKIPPED':<10}  {len(skipped):>3} items")
    print(sep)
    if created:
        print("\nCreated:")
        for item in created:
            print(f"  + {item}")
    if skipped:
        print("\nSkipped (already existed):")
        for item in skipped:
            print(f"  ~ {item}")
    print()


if __name__ == "__main__":
    main()
